# Generated by Django 4.2.7 on 2024-01-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="수강년도")),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("SP", "봄학기"),
                            ("SU", "여름학기"),
                            ("FA", "가을학기"),
                            ("WI", "겨울학기"),
                        ],
                        max_length=2,
                        verbose_name="학기",
                    ),
                ),
                ("is_pass", models.BooleanField(default=False, verbose_name="이수 여부")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "student_set",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subject_set",
                        related_query_name="subject",
                        through="school.Enrollment",
                        to="school.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_set",
                related_query_name="enrollment",
                to="school.student",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollment_set",
                related_query_name="enrollment",
                to="school.subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "subject", "year", "term"),
                name="school_enrollment_unique",
            ),
        ),
    ]
