# Generated by Django 4.2.7 on 2024-01-13 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_point_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follower_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="following_set",
                related_query_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="friend_set",
            field=models.ManyToManyField(
                blank=True,
                related_query_name="friend_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
