# Generated by Django 4.2.7 on 2024-02-07 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_profile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        "^01\\d[ -]?\\d{4}[ -]?\\d{4}$", message="휴대폰 번호 포맷으로 입력해주세요."
                    )
                ],
            ),
        ),
    ]
