# Generated by Django 4.2.7 on 2024-02-13 14:05

import core.model_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_profile_birth_date_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=core.model_fields.DatePickerField(blank=True, null=True),
        ),
    ]
