# Generated by Django 4.2.7 on 2024-02-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_profile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location_point",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
