# Generated by Django 4.2.7 on 2023-12-14 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_auto_20231214_0823"),
    ]

    operations = []
