# Generated by Django 4.2.7 on 2024-01-10 07:43

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_product_alter_post_author_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("event_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        limit_choices_to=shop.models.get_current_date,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.event",
                    ),
                ),
            ],
        ),
    ]
