# Generated by Django 4.2.7 on 2024-01-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0023_alter_post_updated_at"),
        ("weblog", "0004_post_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="weblog_post_set",
                related_query_name="weblog_post",
                to="blog.tag",
            ),
        ),
    ]
