# Generated by Django 4.2.7 on 2024-02-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weblog", "0005_post_tag_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
