# Generated by Django 4.2.11 on 2024-04-01 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studio", "0002_alter_note_options_note_tags_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="note",
            name="like_user_set",
            field=models.ManyToManyField(
                blank=True, related_name="liked_note_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
