# Generated by Django 4.2.7 on 2023-12-15 07:28
import string

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.crypto import get_random_string


def create_user_if_empty(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    is_existed = User.objects.filter(pk=1).exists()
    if is_existed is False:
        username = "auto-" + get_random_string(
            length=10,
            allowed_chars=string.ascii_letters,
        )
        user = User.objects.create_user(
            username=username, password=None, is_active=False, pk=1
        )
        print("user auto generated. pk=", user.pk)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_user_if_empty,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
