# Generated by Django 4.2.7 on 2023-12-16 15:40

from django.db import migrations, models
from django.utils.text import slugify


def update_slug_if_empty(apps, schema_editor):
    Post = apps.get_model("blog.Post")
    post_qs = Post.objects.filter(slug="")
    for post in post_qs:
        post.slug = slugify(post.title, allow_unicode=True)
    Post.objects.bulk_update(post_qs, ["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_category_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                default="",
                help_text="title 값으로부터 자동변환됩니다.",
                max_length=120,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_slug_if_empty,
            migrations.RunPython.noop,
        ),
    ]
