# Generated by Django 4.2.7 on 2023-12-25 15:30

import core.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_unique_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_generic", models.GenericIPAddressField(protocol="IPv4")),
                ("ip_int", core.model_fields.IPv4AddressIntegerField(max_length=15)),
            ],
        ),
    ]
