# Generated by Django 4.2.7 on 2023-12-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("rating", models.SmallIntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "포스팅", "verbose_name_plural": "포스팅 목록"},
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                check=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="blog_review_rating_gte_1_lte_5",
            ),
        ),
    ]
