# Generated by Django 4.2.7 on 2024-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_alter_review_table_comment"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tag",
            name="blog_tag_name_43b6ed_idx",
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["name"],
                name="blog_tag_name_like",
                opclasses=["varchar_pattern_ops"],
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name",), name="blog_tag_name_unique"
            ),
        ),
    ]
