# Generated by Django 4.2.7 on 2024-01-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0018_comment_author_comment_parent_post_tag_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_post_set",
                related_query_name="blog_post",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag_set",
            field=models.ManyToManyField(
                blank=True,
                related_name="blog_post_set",
                related_query_name="blog_post",
                to="blog.tag",
            ),
        ),
    ]
