# Generated by Django 4.2.7 on 2024-01-13 05:49

from django.db import migrations, models
import django.db.models.deletion


def copy_relations(apps, schema_editor):
    Post = apps.get_model("blog", "Post")

    DefaultPostTagRelation = Post.tag_set.through
    PostTagRelation = apps.get_model("blog", "PostTagRelation")

    new_relation_list = []
    for relation in DefaultPostTagRelation.objects.all():
        new_relation = PostTagRelation(
            post_id=relation.post_id,
            tag_id=relation.tag_id,
        )
        new_relation_list.append(new_relation)

    PostTagRelation.objects.bulk_create(new_relation_list, batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_alter_post_author_alter_post_tag_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.tag"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="posttagrelation",
            constraint=models.UniqueConstraint(
                fields=("post", "tag"), name="blog_post_tag_relation_unique"
            ),
        ),
        migrations.RunPython(
            copy_relations,
            migrations.RunPython.noop,
        ),
    ]
