# Generated by Django 4.2.7 on 2024-01-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0022_post_tag_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
