# Generated by Django 4.2.7 on 2024-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0023_alter_post_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[("V", "비공개"), ("P", "공개")],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
