# Generated by Django 4.2.7 on 2024-01-14 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=100),
                ),
                ("rank", models.PositiveSmallIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("cover_url", models.URLField()),
                ("lyrics", models.TextField()),
                ("release_date", models.DateField(verbose_name="발매일")),
                ("like_count", models.PositiveIntegerField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hottrack.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hottrack.artist",
                    ),
                ),
                ("genre_set", models.ManyToManyField(blank=True, to="hottrack.genre")),
            ],
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("name"),
                name="hottrack_genre_name_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["slug"], name="hottrack_so_slug_7cf104_idx"),
        ),
    ]
